[package]
name = "tokio"
version = "0.1.0"
authors = ["kevin <me@kvnvelasco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version="0.2.16", features=['full'] }
futures = "0.3.4"